### ISSUE TITLE
Higher-level collection methods for writes

### ISSUE THREAD

**Issue by willshulman** [objectlabs/leafnode#1]
Many of the native / raw collection methods for write operations have return values that, while very informative and detailed, are cumbersome to work with. 

We should change our implementation of some of these methods to provide a higher level interface while still allowing clients to use the lower-level native Collection methods as well. 

Suggested changes:

(1) The following methods on  the ```DB``` class should take an option ```native``` that is a boolean. If ```native``` is true the Collection returned is a "native" collection (i.e. the raw Collection object used by the native driver. This is the kind of Collection we always return currently. 

* ```getCollection```
* ```getCollections``` (I am ok just getting rid of this method since we have getCollectionNames)
* ```createCollection```

The default value for ```native``` should come from value of ```nativeCollections``` on the DB object which will default to false. 

(2) Add an option to the connect function (in the ```options``` map) called ```nativeCollections``` which will default to false. This value will set the ```nativeCollections``` property of the DB object returned by ```connect```

(3) Change ```Collection.insert``` ```Collection.insertOne``` and ```Collection.insertMany``` to return the object (or objects) inserted (whose _id values may have been generated) or throw an Error   if something went wrong (e.g. wrong number of objects inserted)

(4) Change ```Collection.save``` to return the object saved (I don't think we care to indicated whether it was upserted here) or throw an Error. 

(5) Add an ```updateObject``` method (I think the existing methods take queries and that is a valid interface for some stuff) that takes an object / document as an argument which returns void or throws an Error.

(6) Add a ```removeObject``` method (I think the existing methods take queries and that is a valid interface for some stuff) that takes an object / document as an argument which returns void or throws an Error.

Other thoughts we should discuss before impl:

* Should we just add ```insertObject``` and ```saveObject``` (and maybe ```insertObjects```) and ```updateObject``` and not even bother with the whole "nativeCollection" idea? 
* ```findAndModify``` need anything here? I don't think so
* Should we move this to Carbon before we do it? I am thinking we should leave the leafnode name for now

**Comment by willshulman** [comment]
Ok after discussion we are now thinking we just add ```insertObject``` etc... and do not have two different styles of Collections.

**Comment by willshulman** [comment]
Oh yea. Let's discuss whether we should move this to Carbon.io

**Comment by willshulman** [comment]
BTW there seem to be some bugs in the current impl of the DB class around creating collections. The ```createCollection``` method does not wrap in one case and ```getCollections``` does not wrap results with our Collection class.

**Comment by gregbanks** [comment]
added in carbon-io/leafnode@v0.1.0
